### ISSUE TITLE
Arrange a pipeline to simplify work and implement different algorithms, also plot visualizations for better understanding of dataset.

### ISSUE THREAD

**Issue by Praj-17** [VishalSinghParmar2001/Relating-Social-Media-to-Stock-Movement-Public#9]
### Feature description

Hello there, I am Prajwal Waykos, Data Science and ML enthusiast. I also am very keen on the stock market and have 2 years of stock trading experience.  You can visit my shared links for more information. 

I have the following suggestions.
1. Re-arrange files and codes so that everything runs in a  single click.
2. Have a better understanding of data by the means of detailed, in-depth EDA and some good Data Visualizations.
3. Try a variety of other algorithms as discussed in a previous issue and then do a comparative study on them.
4. Also, as rightly mentioned in the PDF, nothing is certain in the stock market hence we will also need to keep on enlarging our Datasets with their quality.
5. Work on some EDA for better understanding.
6. Work on Data Preprocessing.

I am a GSSOC '22 Participant and want to work on this project for its betterment. 

THE LINK HUB

Email 
1 - pwaykos1@gmail.com
2- prajwal.22010591@viit.ac.in

Resume
https://drive.google.com/file/d/1XG5AX_hk46MBHciLqpEn3w2j_HqlpOev/view?usp=sharing

LinkedIn
https://www.linkedin.com/in/prajwal-waykos-a78105207/

My Website 
http://prajtech.xyz/

Twitter
https://twitter.com/waykos_prajwal

Git Hub
https://github.com/Praj-17

Drive Sharable
https://drive.google.com/drive/u/2/folders/1WTgYq3rXPaE8_qHWLkPcmdkUkz_-ghWP

Tableau 
https://public.tableau.com/app/profile/prajwal.waykos

Hacker Rank
https://www.hackerrank.com/prajwal_22010591

Phone - 
1.- +917249542810
2. - +919405398736

Facebook
https://www.facebook.com/prajwal.waykos

Instagram
https://www.instagram.com/the_resurrection17/

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by mar-galho** [comment]
Hi!

No need to add resume to PRs lol

Do you think you could break down your proposal in different issues? Let me just break down what you've proposed so far:

Re-arrange files and codes so that everything runs in a single click. (this would be awesome)
Have a better understanding of data by the means of detailed, in-depth EDA and some good Data Visualizations. (this would be awesome)
~~Try a variety of other algorithms as discussed in a previous issue and then do a comparative study on them.~~ (#7 )
Enlarging our Datasets with their quality _(I don't see how this could become an issue though)_
~~Work on some EDA for better understanding.~~ (redundant)
~~Work on Data Preprocessing.~~ (#8 is working on this already?)

Let's further the discussion here and work on your proposed tasks!

**Comment by Praj-17** [comment]
Sure ill work on re-arrangement first and then on visualization with in-depth EDA. Please assign these issues to me. As separate issues or in a single issue, whichever you see fit.

**Comment by mar-galho** [comment]
It would be more interesting if you could split the tasks into separate issues - specifically for the GSSoC format, it would be beneficial.

I'll close this issue then and wait for your new ones - I'll assign you to them as soon as you've created them.

**Comment by Praj-17** [comment]
Sure! Go for it.. Waiting! 😇
